### ISSUE TITLE
All slabs in the mod turn into oak slabs when mined.

### ISSUE THREAD

**Issue by DeathByTortoise** [coderbot16/Redwoods#11]
Issue: When mined fir and redwood slabs turn into oak slabs (have not tested stairs but might be good to try asswell)

**Comment by coderbot16** [comment]
This was fixed in #10 and a release will be pushed out shortly.

**Comment by coderbot16** [comment]
Fixed in [version 1.2.3](https://www.curseforge.com/minecraft/mc-mods/redwoods/files/2974693)
