### ISSUE TITLE
Consider adding an Alpine biome

### ISSUE THREAD

**Issue by coderbot16** [coderbot16/Redwoods#2]
Old ExtrabiomesXL had an Alpine biome that was similar to Extreme Hills, but with sparse fir trees. It doesn't look too great, but could be a good optional biome for people who like it.

**Comment by SlayerTheChikken** [comment]
You mean [This one?](https://ftbwiki.org/Alpine) because if so I loved that one for dungeon generation (it blends well) and finding surface ores (for modpacks with all-height ore.)

**Comment by coderbot16** [comment]
Yeah, that’s the one. I plan on adding the Alpine as a disabled-by-default biome in 1.1.0.

**Comment by coderbot16** [comment]
Added in https://github.com/coderbot16/Redwoods/commit/b8f0b62a1dadd07856f46d3f187f6e49124d666e, but it is disabled by default since it doesn't meet the quality standard of the other biomes.

The update has been uploaded and approved on CurseForge as release 1.1.0, have fun!
